services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    container_name: docugen_db
    environment:
      POSTGRES_DB: docugendb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. The Local Email Catcher
  mailhog:
    image: mailhog/mailhog
    container_name: docugen_mailhog
    ports:
      - "1025:1025"   # SMTP port for Spring Boot
      - "8025:8025"   # Web UI (Open localhost:8025 in browser)

volumes:
  pgdata: