spring.application.name=DocuGen Pro


# DATABASE CONFIGURATION

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:docugendb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=your_super_secret_database_password
spring.datasource.driver-class-name=org.postgresql.Driver

# AWS S3 CONFIGURATION

aws.region=${AWS_REGION:eu-west-3}
aws.s3.bucket-name=${S3_BUCKET_NAME:docugen-local-bucket}


# AMAZON SES CONFIGURATION (Replaces Gmail)

spring.mail.host=email-smtp.${AWS_REGION:eu-west-3}.amazonaws.com
spring.mail.port=587
# These MUST be passed via environment variables for security
spring.mail.username=${SES_SMTP_USERNAME:missing_username}
spring.mail.password=${SES_SMTP_PASSWORD:missing_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000 
spring.mail.properties.mail.smtp.timeout=5000


# JPA CONFIGURATION

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# GROQ AI CONFIGURATION

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile


stripe.price.id=${STRIPE_PRICE_ID:price_dummy_for_local}